### ISSUE TITLE
[RFC] Collecting functional requirements.

### ISSUE THREAD

**Issue by djbusstop** [antievictionmappingproject/covid-19-map-react#1]
Continuing the work off this issue: https://github.com/antievictionmappingproject/covid-19-map/issues/160

## Proposal:

1. Collect list of functional requirements
  - Underneath this issue, we can list comment requirements we already know
  - We can use this list to create a **survey** to send to other projects
2. Create issues for these requirements and give them the label "Functional Requirement".
3. Make a project board we can use to order the requirements by priority and decide which ones go in our first release version

@unixjazz You have an idea of how to do the survey and our own listmaking asynchronous. Do you think this is a good way to go about it?

First things first: Do you think this is a good way to go about this? Please comment below!

**Comment by unixjazz** [comment]
@djbusstop I suggest using a pad to sketch the questions between all of us. Once the questions are ready: I will set up the questionnaire on my Nextcloud instance :)  [Here is the pad](https://etherpad.wikimedia.org/p/mapping-software-survey).

**Comment by timhitchins** [comment]
@unixjazz thanks for making the pad.  I will add comments there.
