### ISSUE TITLE
default oral histories map display should not include cities or counties 

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#106]
**should be this:**
[  ] city evictions 
[  ] county evictions 
[X] state/province evictions

<img width="896" alt="" src="https://user-images.githubusercontent.com/41743572/138377430-faec9967-04a5-4f6a-a1b7-dd6dd62d351f.png">

**currently this:**
<img width="893" alt="" src="https://user-images.githubusercontent.com/41743572/138377448-efbf3472-b5c0-488d-aa96-4691da901bac.png">

**Comment by mraguso2** [comment]
PR https://github.com/antievictionmappingproject/covid-19-map-react/pull/110

**Comment by lisjak** [comment]
fixed by #110
