### ISSUE TITLE
rearrange main header links 

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#108]
- given that page language currently defaults to english (LTR reading) + that we land on the OH map, the left-hand link should be the OH map, not the protections map

should be this:
<img width="981" alt="fix" src="https://user-images.githubusercontent.com/41743572/138380851-d58ddd9a-c337-422d-b51d-8a5b83c7f9c9.png">

not this (current state):
 <img width="981" alt="" src="https://user-images.githubusercontent.com/41743572/138380801-f63a3647-75c4-42f9-b5dc-28c8757fad15.png">

**Comment by mraguso2** [comment]
Hi! I can work on this issue now.
