### ISSUE TITLE
Zoom out default setting for story map

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#118]
Right now on the oral history map we have it zoomed in on California. I am wondering if we center it on US so that the story on east coast is also visible? I am not sure how that will affect the visibility of the other stories. I see that they overlap easily, so if there is any way to display them, that would also help. But I think at a minimum we may want to zoom out of CA.

**Comment by lisjak** [comment]
> Can we set all layers on by default? Right now we have just the states on for the oral histories. Thanks!

I think we were using partial layer activation as a workaround while we seek to convert the city point layers to polygons for more cohesion and usability. Do we still want to go ahead and turn all the layers on again? See issue #71

**Comment by tinazarb** [comment]
fixed by #120
