### ISSUE TITLE
"Zoom out" key on protections map

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#119]
On the protections map the red icons are not visible without having to scroll. I have attached two images - one of how it currently is vs how I would like it to display. Basically just showing what the red icons mean by default. If you zoom out on your browser you see that this happens naturally.

![image](https://user-images.githubusercontent.com/35778453/148656499-b54900de-209c-46b7-b4a7-13129cdf9535.png)

![image](https://user-images.githubusercontent.com/35778453/148656587-a67d7162-8505-4e27-8b40-de0cba12198c.png)

**Comment by tinazarb** [comment]
fixed by #120
