### ISSUE TITLE
Change "evictions" to "protections" on protections map layers panel

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#123]
![image](https://user-images.githubusercontent.com/35778453/150619599-10f27690-3710-4c13-a386-e7c5b6f49c1d.png)

Looks like some wires may have got crossed between the two maps. On the protections map layers panel, "evictions" should say "protections" for city, county, and state/province.

**Comment by lisjak** [comment]
solved by #124
