### ISSUE TITLE
Remove content reducer

### ISSUE THREAD

**Issue by c5inco** [antievictionmappingproject/covid-19-map-react#22]
I think this needs more detail - maybe @djbusstop or @timhitchins  can provide some?

**Comment by josuebustos** [comment]
Hi @c5inco,

I was wondering if this open issue has more details and or owner?

**Comment by c5inco** [comment]
No owner at the moment. And waiting on details. I think @djbusstop may take it though.

**Comment by c5inco** [comment]
After reviewing with @djbusstop, it looks like we are using the reducer, so closing this issue.
