### ISSUE TITLE
New line on housing protection legislation popups

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map-react#25]
Yesterday we talked about adding a text line like this below to all housing protection legislation popups. It would make sense to have it below the protection end dates and above the policy summary. It would say:

"If your local city or county protections have expired you may still be protected under state or national legislation."

**Comment by c5inco** [comment]
@isthewhiz did you still want to add this?

**Comment by isthewhiz** [comment]
Yes, I didn’t get a chance to get clarification from Brett
