### ISSUE TITLE
Layer order should be as defined in "map-layers"

### ISSUE THREAD

**Issue by c5inco** [antievictionmappingproject/covid-19-map-react#29]
Details from meeting:

**River**: there is an order on each object 1 closer to top 4 closer to bottom. Rent strikes should be above cities, cities should be above counties, counties should be above nations
**Melissa**: was that a regression?
**River**: You mean why this was happening? I think I know. There's a property called `pane` in the pmap component which is coming from the React Leaflet. That worked but when the svg layers came in it might have broken it. If I was working on this that's where I'd start

**Comment by djbusstop** [comment]
I fixed this issue by changing the z-index calculation in the pane component.
