### ISSUE TITLE
Zoom out (-) button not really working

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#33]
The - (minus) button is not working as well as the + (plus) button. When you hover over the + button you can see that it is clickable, whereas the minus button does not signifying this, and it doesn't work right away for some reason. After exploring the map for several minutes it started to work - so not sure if this has anything to do with some sort of loading issue? I tested it on Safari and Chrome, and issue appeared at the onset on both browsers.

**Comment by colemanmoore** [comment]
From what I can tell this happens only before you zoom in, when the "minus" button is disabled from Leaflet's perspective (`a.leaflet-disabled` has `cursor:default` style rule). Once you zoom in, leaflet enables that link element and the style changes to `cursor:pointer`. I would say this isn't a bug but might be unwanted behavior.

**Comment by lisjak** [comment]
@brett-halperin Please see PR #52 ⬆️

**Comment by lisjak** [comment]
fix included in PR #83
