### ISSUE TITLE
InfoWindow does not shows Eviction Status correctly

### ISSUE THREAD

**Issue by djbusstop** [antievictionmappingproject/covid-19-map-react#35]
**Live site infowindow for Oregon**
![Live site infowindow for Oregon](https://user-images.githubusercontent.com/41007222/108634852-9f715d80-7473-11eb-85fc-110cec425c3d.png)

**Comment by c5inco** [comment]
Could we add an example / location that this bug shows up?

**Comment by erinmcel** [comment]
Right now, the field eviction status appears in the live map in the popup, but not the React map.
