### ISSUE TITLE
Zoom out more as default setting (idk what to call this)

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#36]
Idk what to call this exactly but I am talking about the level of zoom that first loads when a user comes to the map. Would like for this to be at parity with the current version if possible, so that more regions are visible. See two screenshots below. The more distant one is preferred.  
<img width="1247" alt="Screen Shot 2021-02-21 at 1 34 33 PM" src="https://user-images.githubusercontent.com/35778453/108634912-198cec80-744a-11eb-8753-794e154fd7bf.png">
<img width="1291" alt="Screen Shot 2021-02-21 at 1 34 39 PM" src="https://user-images.githubusercontent.com/35778453/108634913-1a258300-744a-11eb-8c20-61b956ee27fb.png">

**Comment by c5inco** [comment]
The request is to just zoom the map surface itself out, and not make the map controls smaller right?

Or is it both? I think if both, we have the map controls sizing request covered with this #28?

**Comment by brett-halperin** [comment]
> The request is to just zoom the map surface itself out, and not make the map controls smaller right?
> 
> Or is it both? I think if both, we have the map controls sizing request covered with this #28?

Right just the map surface itself!

**Comment by lisjak** [comment]
@brett-halperin Please see PR #52 ⬆️

**Comment by lisjak** [comment]
fix included in PR #83
