### ISSUE TITLE
Typo in intro text to be fixed

### ISSUE THREAD

**Issue by erinmcel** [antievictionmappingproject/covid-19-map-react#43]
![Screen Shot 2021-03-05 at 7 49 59 AM](https://user-images.githubusercontent.com/8007917/110120390-fb4cb800-7d8a-11eb-970b-7011e8cf693d.png)
Highlighted sentences have minor typos. 

Should be "Colonial and nation-state**s**"

and

"**the** development of this map

**Comment by 96RadhikaJadhav** [comment]
@erinmcel  Can I work on the issue if no one is working on it?

**Comment by isthewhiz** [comment]
@96RadhikaJadhav did you start on this issue? @erinmcel I looked and would need to make the changes in all the files should have it corrected by tomorrow.

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav did you start on this issue? @erinmcel I looked and would need to make the changes in all the files should have it corrected by tomorrow.

@isthewhiz Yes I created a PR. @erinmcel  Could you please check and let me know if any changes needs to be done.
