### ISSUE TITLE
Add "Last updated" info to the Info popup

### ISSUE THREAD

**Issue by c5inco** [antievictionmappingproject/covid-19-map-react#46]
We have this field in our database, so it would be useful to show this on the info popup to give users a sense of how recent the data is, specifically when looking for information on moratoriums.

**Comment by c5inco** [comment]
@brett-halperin I think is easy to query but probably should include this in the overall visual changes for the Info popup with the evictions status discussion.

**Comment by c5inco** [comment]
@unixjazz @azadag do either of you know the exact column name for this field in Carto?

**Comment by c5inco** [comment]
Column name is `reviewed_date` - incoming PR now!

**Comment by lisjak** [comment]
Completed by PR #93
