### ISSUE TITLE
Carto <-> Airtable web service

### ISSUE THREAD

**Issue by c5inco** [antievictionmappingproject/covid-19-map-react#49]
Tracking bug for work to build better data pipeline so Carto can query Airtable more directly.

**Comment by azadag** [comment]
I think i want to set up some sort of github action to automatically do the data sync, will have to learn to set this up though!

**Comment by azadag** [comment]
Ok this is finished... new data can be found at [https://ampitup.carto.com/dataset/global_housing_actions](https://ampitup.carto.com/dataset/global_housing_actions) exported here.  See [old link for reference](https://ampitup.carto.com/dataset/emergency_housing_actions), and [airtable base ](https://airtable.com/apphQ0Qjb5QuxXbrK/tbleQnBFIF1vnjc1e/viwUJOIsRWLVuy6BU?blocks=hide)

New variables names with comparison to old variable names (in quotes)
variables starting with **housing_exp_** and **housing_part__** are width-wise expansions + english only translations of airtable variable **housing_experience_type**;  and **housing_justice_participation_3**

**carto variables + old version if existed**
id
local_neighb_city_state_country = 'location'
Latitude
Longitude
participation_reason = 'why'
num_occupants_involved
debt
housing_exp_eviction
housing_exp_housing_justice_action
housing_exp_landlord_retaliation
experienced_landlord_retaliation
date_recieved_communication
housing_part_campaigning_list_of_demands
housing_part_mutual_aid_direct_aid
housing_part_occupation_squat
housing_part_other
housing_part_rent_strike_rent_decrease
property_ll_owner
local_resources

**Comment by unixjazz** [comment]
hi @azadag: what do you need help with?

**Comment by azadag** [comment]
Oh! I think reviewing the data types, variable names, etc to prepare for swapping out the old version? 
Am I outputting data correctly (NULL vs empty cells).
