### ISSUE TITLE
linter/code formatter + config

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#54]
Hi all,

Would like input on some additional repo-specific rules to standardize things like whitespace, tabs, etc for all contributors. 

The `prettierrc.json` is currently as such: 
```
{
  "singleQuote": true,
  "arrowParens": "avoid",
  "trailingComma": "es5",
  "semi": true
}
```

Below are some additional rules for the `prettierrc.json` config file that I recommend we specify.
```
{
  "singleQuote": true,
  "arrowParens": "avoid",
  "trailingComma": "es5",
  "semi": true,
  "tabWidth": 4,
  "jsxBracketSameLine": true,
  "bracketSpacing": true,
  "printWidth": 80
}
```
Please see the [Prettier Docs](https://prettier.io/docs/en/options.html) for additional information. 

As for ESLint, I see that we've currently specified the config in the package.json is: 
```
"eslintConfig": {
  "extends": "react-app"
},
```

Would the addition of ESLint's recommended ruleset [(see here)](https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js) be useful?

**Comment by c5inco** [comment]
I think this looks good to me - I don't have any strong opinions about it. Curious what @benjaminben @djbusstop @jimboweb think.
