### ISSUE TITLE
dependency issues with leaflet, react-leaflet and react-leaflet/core

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#55]
Hi all, 
I'm unsure of whether these dependency updates are necessary globally or whether it was an issues specific to my local environment running node version 16.2.0 on Mac OS. I encountered a persistent [Module parse failed: Unexpected token (10:41) in @react-leaflet/core/esm/path.js](https://github.com/PaulLeCam/react-leaflet/issues/877) (among other issues related to node version incompatibilities that I was able to fix) and used the following commands to ultimately rectify the dependency issues: 
```
npm install --save-exact leaflet@1.7.1
npm install --save-exact react-leaflet@3.1.0
npm install --save-exact @react-leaflet/core@1.0.2
```
Downgrading node to v14.15.0 and then recloning the repo allowed me to `npm install` with no error, and no errors were encountered on `npm run start`. Modifications to the dependencies as specified above are compatible with node v14.15.0. 

Would it be of value to modify the dependencies in `package.json` in the following way to avoid incompatibility issues with newer versions of node?

`"react-leaflet": "^3.0.2"` to `"react-leaflet": "3.1.0"`
`"leaflet": "^1.7.1"` to `"leaflet": "1.7.1"`
and the addition of `@react-leaflet/core": "1.0.2"`

**Comment by c5inco** [comment]
FWIW I'm on node v15.11.0 and haven't had these issues. I think it's fine to upgrade leaflet (and the related React dependencies), and also don't mind upgrading node on my machine. But curious what @benjaminben @jimboweb @djbusstop think based on their local machine configuration.
