### ISSUE TITLE
link main text in header to AEMP website

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#66]
- make ‘The Anti-Eviction Mapping Project’ text in the header link to the AEMP website (https://antievictionmap.com/) 

![image](https://user-images.githubusercontent.com/41743572/125209252-912aaf00-e265-11eb-9843-ad162bb1179a.png)

**Comment by brett-halperin** [comment]
Thanks for making this issue Lisa! If we could also decrease the size of the text by 5-10 that would be great!

**Comment by swarup4741** [comment]
Can I work on this issue ? Other than linking the header to the given link do i have to change the font size ?

**Comment by lisjak** [comment]
@swarup4741 if you'd prefer not to work on the font size issue in addition to linking, just be sure to create a GitHub issue for it so someone else can pick it up! :)

**Comment by swarup4741** [comment]
<img width="759" alt="coviderror" src="https://user-images.githubusercontent.com/69234404/125411734-2e056a5e-08fb-4304-8e65-d9b70a83c988.PNG">

I'm getting this error while installing the dependencies.... i have node `v 16.4.2` ... is that what causing the problem ?

**Comment by lisjak** [comment]
@swarup4741 There is a solution in #55 that should help you rectify this!

**Comment by swarup4741** [comment]
<img width="778" alt="outdated" src="https://user-images.githubusercontent.com/69234404/125479652-85bc97a7-18e1-47d4-bbde-412a7902a989.PNG">

I tried to update certain dependencies but it didn't work... here are listed of outdated dependencies and updating is being prevented... so shall i update their versions in `package.json` then install them ?

**Comment by swarup4741** [comment]
<img width="555" alt="err" src="https://user-images.githubusercontent.com/69234404/125486333-ef146314-9729-49b3-ab30-8cefc7c6439f.PNG">

Even after updating the `@react-leaflet/core` the error is still showing

**Comment by lisjak** [comment]
[commit 65a1fb4ad2b599de68fd227e089289cb353c0442](https://github.com/antievictionmappingproject/covid-19-map-react/commit/65a1fb4ad2b599de68fd227e089289cb353c0442) solves this
