### ISSUE TITLE
Fix key on protections map 

### ISSUE THREAD

**Issue by brett-halperin** [antievictionmappingproject/covid-19-map-react#76]
This is how it is appearing on the prototype link

![image](https://user-images.githubusercontent.com/35778453/125211661-deeee980-e25c-11eb-95bd-566c06a24de9.png)

**Comment by boraerden** [comment]
fixed with https://github.com/antievictionmappingproject/covid-19-map-react/commit/d1278b107b201724283b5f6759ee52eeaebb1a98
